# A Python Quick Start Tutorial - Part 2
## by Peter Mackenzie-Helnwein
University of Washington, Seattle, WA

pmackenz@uw.edu          
https://www.ce.washington.edu/facultyfinder/peter-mackenzie-helnwein

# Matrix Data Types

While tuples and lists in python may look like vectors in MATLAB, they behave as sets and **not as vectors**!  Let that be illustrated by what may look at first like a vector operation (addition):

In [1]:
a=[1,2,3]
b=[4,5,6]

In [2]:
a + b

[1, 2, 3, 4, 5, 6]

In [3]:
b + a

[4, 5, 6, 1, 2, 3]

We see that the "+" concattenates lists.  Let's try multiplication:

In [4]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

We observe that "*" is raising a TypeError, i.e., this operation is not even defined for lists.

The next section will introcuce the proper data types for vector, matrix, and tensor operations.

## array and matrix classes using numpy

Python provides an extension named **numpy** that provides data types for vector, matrix, and tensor operations.  Moreover, **numpy** provides vectorices algebraic operations and solvers.

First, we need to load the numpy module

In [5]:
import numpy as np

The most common data types are array and matrix.  The array constructor takes a list (vector), list of lists (matrix/2nd-order tensor), list of list of lists (3rd-order tensor), while the matrix constructor requires a list of lists (matrix) as the input.  matrix is pretty much the MATLAB equivalent, showing similar limitations.  array is the preferred, more general tensor type.

$$
{\bf A}=
{\bf B}=
\left[
\begin{array}{cc}
 1 & 2 \\
 3 & 4
\end{array}
\right]
$$

In [6]:
A=np.array([[1,2],[3,4]])
B=np.matrix([[1,2],[3,4]])

In [7]:
A

array([[1, 2],
       [3, 4]])

In [8]:
print(A)

[[1 2]
 [3 4]]


In [9]:
B

matrix([[1, 2],
        [3, 4]])

In [10]:
print(B)

[[1 2]
 [3 4]]


Keep in mind that while the printed versions of matrix and array objects are identical, their behavior is not!

1. **matrix** follows the familiar MATLAB (or octave) syntax with minor differences:
    1. B*C is the matrix product
    2. transpose of B -> B.T
    3. inverse of B -> B.I
2. **array** follows tensor algebra notation
    1. A*B is element by element multiplication.
    2. A@B is the tensor contraction (dot product of adjacent slots; matrix product for 2nd-order tensors)
    2. transpose of A -> A.T
    3. inverse of A -> A.I
    

In [11]:
A

array([[1, 2],
       [3, 4]])

In [12]:
A*A

array([[ 1,  4],
       [ 9, 16]])

A is an array, thus, A*A is the element by element product -> each element is squared

We get the matrix product using the @ operator (python 3.5 and later)

In [13]:
A@A

array([[ 7, 10],
       [15, 22]])

In [14]:
B

matrix([[1, 2],
        [3, 4]])

In [15]:
B*B

matrix([[ 7, 10],
        [15, 22]])

B is a matrix, thus, B*B is the matrix product.  The result is identical to A@A using the array class

### A simple example using basic operations shall illustrate the similarities and differences even further.

1. create two vectors $$u=\left\{\begin{array}{c}1\\2\\3\end{array}\right\} \qquad\text{and}\qquad v=\left\{\begin{array}{c}4\\5\\6\end{array}\right\}$$

In [16]:
u=np.array([1,2,3])
v=np.array([4,5,6])
print(u)
print(v)

[1 2 3]
[4 5 6]


2. compute the sum: $u + v$

In [17]:
u+v

array([5, 7, 9])

3. compute the dot product: $u\cdot v$
(in index notation, this yields a scalar $u_k v_k$)

In [18]:
np.dot(u,v)

32

In [19]:
u.dot(v)

32

In [20]:
v.dot(u)

32

In [21]:
u@v

32

All four of the above techniques work.  The first invokes numpy's **dot** function, the second and third invoke the array-class **dot** method (more on that later), and the last utilizes the contraction operator, @.

4. compute the outer product: $u\otimes v$
(in index notation, this is yields a 2nd-order tensor with components $u_i v_j$)

In [22]:
np.outer(u,v)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

Note that $u$ and $v$ are one-dimensional arrays while the outer product combines them into a two-dimensional array, just as proper tensor operations should do.

Now let's repeat that exercise using the matrix class.  The key difference is that all objects are now matrices and vectors are represented as columns (nx1) or rows (1xn), i.e., two-dimensional objects just as in MATLAB.


1. create two vectors $$u=\left\{\begin{array}{c}1\\2\\3\end{array}\right\} \qquad\text{and}\qquad v=\left\{\begin{array}{c}4\\5\\6\end{array}\right\}$$

In [23]:
# as row vectors ...
u=np.matrix([1,2,3])
v=np.matrix([4,5,6])
print(u)
print(v)

[[1 2 3]]
[[4 5 6]]


In [24]:
# as column vectors (as in shown in the problem statement) ...
u=np.matrix([[1],[2],[3]])
v=np.matrix([[4],[5],[6]])
print(u)
print(v)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


2. compute the sum: $u + v$

In [25]:
u+v

matrix([[5],
        [7],
        [9]])

3. compute the dot product: $u\cdot v$
(in index notation, this yields a scalar $u_k v_k$)

In [26]:
u.T*v

matrix([[32]])

The transposition (.T) vonverts u into a row vector and the matrix product converts the result into a 1x1 matrix.  MATLAB shows such a 1x1 matrix as a scalar, though internally it remains a matrix.  This is quite different from the array class which performed the proper reduction in order.

Note: the np.dot product fails since a (3x1) matrix cannot be multiplied with a (3x1) matrix:

In [27]:
np.dot(u,v)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

4. compute the outer product: $u\otimes v$
(in index notation, this is yields a 2nd-order tensor with components $u_i v_j$)

In [28]:
u*v.T

matrix([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])

Comparing this form explains while the outer product is sometimes called "the wrong dot product" (mostly by MATLAB users).

### Linear algebra in numpy

**numpy** comes with a comprehensive package of linear algebra functionality.  Since those extensions take time to load and eat up memory on your computer, we only load functions that we actually use in our code.  Let's illustrate this by solving a system of equations

$$
\left[\begin{array}{cccc}5&3&1&0\\3&5&3&1\\1&3&5&3\\0&1&3&5\end{array}\right]
\left\{\begin{array}{c}x_0\\x_1\\x_2\\x_3\end{array}\right\}
=
\left\{\begin{array}{c}2\\3\\1\\-1\end{array}\right\}
$$


In [29]:
from numpy.linalg import solve

A=np.array([[5,3,1,0],[3,5,3,1],[1,3,5,3],[0,1,3,5]])
y=np.array([2,3,1,-1])

In [30]:
x=solve(A,y)

In [31]:
print(x)

[ 0.00000000e+00  6.66666667e-01  3.70074342e-17 -3.33333333e-01]


We can access linear algebra functions directly without loading them into the local namespace.  We demonstrate this by solving th eeigenvalue problem:
$$
{\bf A}\cdot {\bf n}=\lambda {\bf n}
$$
where $A$ is the matrix defined in the previous problem.

In [32]:
(lam,vec)=np.linalg.eig(A)

We obtain the eigenvalues as

In [33]:
print(lam)

[10.77200187  6.          2.22799813  1.        ]


and the respective eigenvectors as

In [34]:
print(vec)

[[ 0.40276437  0.63245553  0.58118918 -0.31622777]
 [ 0.58118918  0.31622777 -0.40276437  0.63245553]
 [ 0.58118918 -0.31622777 -0.40276437 -0.63245553]
 [ 0.40276437 -0.63245553  0.58118918  0.31622777]]


Let's verify that the result is correct by substituting the obtained $i$-th vectors into the original eigenvalue problem to test
$$
({\bf A}\cdot {\bf n}_i - \lambda_i {\bf n}_i)={\bf 0}
\quad\Rightarrow\quad
||({\bf A}\cdot {\bf n}_i - \lambda_i {\bf n}_i)||={ 0}
$$

In [37]:
for i in range(4):
    w = A@vec[:,i] - lam[i]*vec[:,i]
    print("solution {} yields norm {:12.3e}".format(i,np.linalg.norm(w)))


solution 0 yields norm    8.379e-15
solution 1 yields norm    3.878e-15
solution 2 yields norm    3.625e-15
solution 3 yields norm    1.243e-15


A quicker way could be verifying that the following expression returns a zero matrix (with numerical zero being a number around $10^{-16}$ or 1.e-16 in computer lingo)

In [ ]:
np.linalg.norm(vec.T @ A @ vec - np.diag(lam))

Please check https://numpy.org/doc/stable/reference/routines.linalg.html for more available functions.

An extension to **numpy**'s capabilities is distributed as **scipy** (https://docs.scipy.org/doc/scipy/reference/api.html).  **scipy** provides, among many other functions, tools for
* sparse matrices and tools to work on those
* spectral analysis (fft)
* statistics
* optimization
* image processing
* signal processing

<hr>

[Jump to chapter 1: Basic Concepts](./01%20Basic%20Concepts.ipynb)

[Jump to chapter 3: Plotting](./03%20Plotting%20using%20matplotlib.ipynb)

[Back to the outline](./00%20Outline.ipynb)