# A Python Quick Start Tutorial
# Lesson \#3 : Loops & Matrix Operations
## by Peter Mackenzie-Helnwein - <font color=red>SOLUTION</font>
University of Washington, Seattle, WA

pmackenz@uw.edu          
https://www.ce.washington.edu/facultyfinder/peter-mackenzie-helnwein

## Resources (reminder)

   1. Python Docs: https://docs.python.org/3/
   
   1. Python Tutorial (comprehensive): https://docs.python.org/3/tutorial/index.html
   
   1. Python Library Reference (the nitty-gritty details): https://docs.python.org/3/library/index.html
   
   1. Everything else: http://google.com
   

## Discussing questions from the self-study assignment

This section is to discuss your questions


### Exercise 1: Looping over dictionaries

**Given**:
A dictionary `your_course` is given as follows (please do a `shift-enter` to initialize it)

In [1]:
your_course = {
               'department':'CEE',
               'group':'CESG',
               'number':'505 A&B',
               'complexity':10,
               'workload':0,
               'credits':3,
               'instructor':'Dr Peter'
              }

**Your tasks**:
1. Write a loop to print all keys, one per line

In [2]:
for k in your_course:
    print(k)

department
group
number
complexity
workload
credits
instructor


2. Change complexity to 6 and workload to 8

In [3]:
your_course['complexity']=6
your_course['workload']=8

3. copy and modify the loop from 1. to print "key: value", one per line

In [4]:
for k in your_course:
    print("{:12s}: {}".format(k, your_course[k]))

department  : CEE
group       : CESG
number      : 505 A&B
complexity  : 6
workload    : 8
credits     : 3
instructor  : Dr Peter


4. Write a condition that checks if `your_course` has a field named `'expected_grade'`.
    - If the field DOES exist, print **"Field exists with value of {:3.1f}".format(_the value associated with that key_)"**
    - If the field DOES NOT exist, create it and assign a sensible value, the print **"Field created with value of {:3.1f}".format(_the value associated with that key_)"**

In [5]:
if 'expected_grade' in your_course:
    print("Field exists with value of {:3.1f}".format(your_course['expected_grade']))
else:
    your_course['expected_grade'] = 4.0
    print("Field created with value of {:3.1f}".format(your_course['expected_grade']))

Field created with value of 4.0


Execute the above code again to verify that the new key/value pair was added

In [6]:
if 'expected_grade' in your_course:
    print("Field exists with value of {:3.1f}".format(your_course['expected_grade']))
else:
    your_course['expected_grade'] = 4.0
    print("Field created with value of {:3.1f}".format(your_course['expected_grade']))

Field exists with value of 4.0


In [7]:
for k in your_course:
    print("{:12s}: {}".format(k, your_course[k]))

department  : CEE
group       : CESG
number      : 505 A&B
complexity  : 6
workload    : 8
credits     : 3
instructor  : Dr Peter
expected_grade: 4.0


### Exercise 2: Looping over Strings

Strings are "Lists of characters". Thus, you can loop through a string.

Moreover, multi-line text is also just a single string with newline characters ('\n') separating lines.

Consider the following string (a poem by Phillis Wheatley, the first African-American author of a published book of poetry):

In [19]:
s = """'Twas mercy brought me from my Pagan land,
Taught my benighted soul to understand
That there's a God, that there's a Saviour too:
Once I redemption neither sought nor knew.
Some view our sable race with scornful eye,
"Their colour is a diabolic die."
Remember, Christians, Negros, black as Cain,
May be refin'd, and join th' angelic train.

            BY PHILLIS WHEATLEY """

We used `"""..."""` to define a multi-line string.  While this looks nice, it is still a single string as can be verified by the next command.

In [20]:
s

'\'Twas mercy brought me from my Pagan land,\nTaught my benighted soul to understand\nThat there\'s a God, that there\'s a Saviour too:\nOnce I redemption neither sought nor knew.\nSome view our sable race with scornful eye,\n"Their colour is a diabolic die."\nRemember, Christians, Negros, black as Cain,\nMay be refin\'d, and join th\' angelic train.\n\n            BY PHILLIS WHEATLEY '

Note the `\n` in this string?  This example actually shows the difference between just typing the variable `s` (above) or using the `print()` command.

In [21]:
print(s)

'Twas mercy brought me from my Pagan land,
Taught my benighted soul to understand
That there's a God, that there's a Saviour too:
Once I redemption neither sought nor knew.
Some view our sable race with scornful eye,
"Their colour is a diabolic die."
Remember, Christians, Negros, black as Cain,
May be refin'd, and join th' angelic train.

            BY PHILLIS WHEATLEY 


**Your task**:
Write code that counts and outputs
1. The number of lines in the string `s`.
2. The number of non-whitespace characters (whitespace is `' '`, `'\t'` (tab), `'\n'` (newline)
3. The number of words.

In [22]:
print('\\t')

\t


In [26]:
# list of white space chars (tuple, actually)
whitespace = (' ','\n','\t','\0')

# initialize counters
num_lines = 1
num_chars = 0
num_words = 0

# do the counting
last_char = ''
for char in s:
    if char=='\n':
        num_lines += 1
    if char not in whitespace:
        num_chars += 1
    else:
        if  last_char not in whitespace:
            num_words += 1
    last_char = char
        
print("Found {} lines".format(num_lines))
print("Found {} printable characters".format(num_chars))
print("Found {} words".format(num_words))

Found 10 lines
Found 299 printable characters
Found 61 words


### Exercise 3: Some linear algebra

**Theory**: 
The eigenvalue problem for a symmetric matrix ${\bf A}$ is defined as
$$
    ({\bf A}-\lambda_i {\bf 1})\,{\bf n_i} = {\bf 0}
$$
where $\lambda_i$ is the $i^{th}$ eigenvalue and ${\bf n}$ is the  $i^{th}$ eigenvector.

Pre-multiplying this equation with the eigenvector yields
$$
    {\bf n_i}\cdot({\bf A}-\lambda_i {\bf 1})\,{\bf n_i} = 0
    \quad\Rightarrow\quad
    \lambda_i = \frac{{\bf n_i}\cdot{\bf A}\cdot{\bf n_i}}{{\bf n_i}\cdot{\bf n_i}}
$$
The expression for $\lambda_i$ is the _Rayleigh coefficient_.

**Your tasks**:
1. use `numpy.linalg.eig` to solve to find eigenvalues and eigenvectors of the given matrix ${\bf A}$
2. in a loop, verify that the _Rayleigh coefficient_ indeed yields the eigenvalues.
3. test, whether or not the following expression is true
   $$
      \text{for}~~{\bf v}=\frac{\sqrt{2}}{2}({\bf n}_1+{\bf n}_2)
      \quad\to\quad
      \frac{{\bf v}\cdot{\bf A}\cdot{\bf v}}{{\bf v}\cdot{\bf v}} = \frac{\lambda_1 + \lambda_2}{2}
   $$
   whill this result hold for ${\bf v}=({\bf n}_1+{\bf n}_2)$?

In [39]:
# GIVEN ... please execute this cell to initialize A

from numpy import array

A = array(
    [[3,2,1,0,0],
     [2,3,2,1,0],
     [1,2,3,2,1],
     [0,1,2,3,2],
     [0,0,1,2,3]]
)

I define helper functions to compute the Rayleigh coefficient and to perform a relaxed floating point comparison

In [44]:
def rayleigh(A,v):
    q = v@v
    if q>0.0:
        ans = v@A@v/q
    else:
        raise
    return ans

def test_equal(a,b):
    if abs(b-a) < 1.e-12:
        return True
    else:
        return False

In [45]:
from numpy import sqrt
from numpy.linalg import eig

# 1. *****************
lam,nvec = eig(A)
print(lam)
print(nvec)

[7.65427349 4.56155281 1.74770274 0.43844719 0.59802377]
[[ 3.28733703e-01  5.57345410e-01  6.17548407e-01  4.35162146e-01
   1.02801351e-01]
 [ 4.85676469e-01  4.35162146e-01 -1.78297793e-01 -5.57345410e-01
  -4.82004424e-01]
 [ 5.58663621e-01 -6.11410290e-16 -4.16758592e-01 -3.92388876e-15
   7.17082447e-01]
 [ 4.85676469e-01 -4.35162146e-01 -1.78297793e-01  5.57345410e-01
  -4.82004424e-01]
 [ 3.28733703e-01 -5.57345410e-01  6.17548407e-01 -4.35162146e-01
   1.02801351e-01]]


In [46]:
# 2. *****************

template = "from eig: {:16.12f} <=> Rayleigh: {:16.12f}   => {}"

# ... wrong way
for pair in zip(lam,nvec):
    lamR = rayleigh(A,pair[1])
    print(template.format(pair[0],lamR, test_equal(pair[0],lamR)))
    
print('----')
# ... correct way
for pair in zip(lam,nvec.T):
    lamR = rayleigh(A,pair[1])
    print(template.format(pair[0],lamR, test_equal(pair[0],lamR))) 

from eig:   7.654273492980 <=> Rayleigh:   7.381558569180   => False
from eig:   4.561552812809 <=> Rayleigh:   4.520723212062   => False
from eig:   1.747702740583 <=> Rayleigh:   1.936643730918   => False
from eig:   0.438447187191 <=> Rayleigh:   0.506515417796   => False
from eig:   0.598023766437 <=> Rayleigh:   0.654559070044   => False
----
from eig:   7.654273492980 <=> Rayleigh:   7.654273492980   => True
from eig:   4.561552812809 <=> Rayleigh:   4.561552812809   => True
from eig:   1.747702740583 <=> Rayleigh:   1.747702740583   => True
from eig:   0.438447187191 <=> Rayleigh:   0.438447187191   => True
from eig:   0.598023766437 <=> Rayleigh:   0.598023766437   => True


In [47]:
# 3.a  *****************
v = (nvec[:,0]+nvec[:,1])/sqrt(2)
rhs = (lam[0]+lam[1])/2
lhs = rayleigh(A,v)
print("lam1+lam2: {:16.12f} <=> Rayleigh: {:16.12f}   => {}".format(rhs,lhs,test_equal(rhs,lhs)))

# 3.b  *****************
v = (nvec[:,0]+nvec[:,1])
rhs = (lam[0]+lam[1])/2
lhs = rayleigh(A,v)
print("lam1+lam2: {:16.12f} <=> Rayleigh: {:16.12f}   => {}".format(rhs,lhs,test_equal(rhs,lhs)))

lam1+lam2:   6.107913152894 <=> Rayleigh:   6.107913152894   => True
lam1+lam2:   6.107913152894 <=> Rayleigh:   6.107913152894   => True


### Exercise 4: Conversion from MATLAB

You may already have some MATLAB code that you want to migrate to python.  Using the `matrix` type is a quick and dirty way, though using `array` is the _highly_ recommended way.

Using the `array` type, try converting this MATLAB code segment into python

~~~
x = linspace(0,10,11)';
x2 = x.*x;              # generates a list of x^2
one = ones(11,1);       # a vector full of ones
y = sin(pi*x/10);

A = [ one'*one, one'*x, one'*x2
        x'*one,   x'*x,   x'*x2
       x2'*one,  x2'*x,  x2'*x2 ];

b = [ y'*one; y'*x; y'*x2 ];

p = A\b

ybar = [ one, x, x2 ]*p;

errvec = y-ybar;

err = sqrt((errvec'*errvec)/length(x))
~~~

which generates

~~~
p =

  -0.025578
   0.399704
  -0.039970

err =  0.021912
~~~

**hints**:
1. Think vector as 1D-array and matrix as 2D-array
2. think matrix or dot product -> @
3. the `numpy.hstack` or `numpy.vstack` function may come in handy

In [37]:
from numpy import array,linspace, sqrt, sin, ones, pi, vstack, hstack
from numpy.linalg import solve

x = linspace(0,10,11)
x2 = x*x               # generates a list of x^2
one = ones(11)         # a vector full of ones
y = sin(pi*x/10.)

A = array([[one@one, one@x, one@x2 ],
           [  x@one,   x@x,   x@x2 ],
           [ x2@one,  x2@x,  x2@x2 ]])

b = array([ y@one, y@x, y@x2 ])

p = solve(A,b)

# ybar = p@array([one,x,x2])
ybar = array([one,x,x2]).T@p

errvec = y-ybar

err = sqrt((errvec@errvec)/len(x))

print("parameters p = {}".format(p))
print("error = {}".format(err))

parameters p = [-0.02557832  0.39970382 -0.03997038]
error = 0.021911970681663454


In [30]:
[one,x,x2]

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])]

In [34]:
p @ array([one,x,x2])

array([-0.02557832,  0.33415512,  0.61394779,  0.8137997 ,  0.93371085,
        0.97368123,  0.93371085,  0.8137997 ,  0.61394779,  0.33415512,
       -0.02557832])

In [33]:
array([one,x,x2]).T @ p

array([-0.02557832,  0.33415512,  0.61394779,  0.8137997 ,  0.93371085,
        0.97368123,  0.93371085,  0.8137997 ,  0.61394779,  0.33415512,
       -0.02557832])

## Homework questions

We can all learn from your questions!